<?php
/**
 * SalesTrack Web Database Installer & Auto-Scanner Setup Assistant
 */
set_time_limit(60);
$message = null;
$messageType = null;
$foundHost = null;

$dbHost = $_POST['db_host'] ?? 'sql302.infinityfree.com';
$dbName = $_POST['db_name'] ?? 'if0_42783325_salestrack2';
$dbUser = $_POST['db_user'] ?? 'if0_42783325';
$dbPass = $_POST['db_pass'] ?? 'Patrick121603';

// AUTO-RUN ON PAGE LOAD IF NOT CONFIGURED YET
if ($_SERVER['REQUEST_METHOD'] === 'GET' && !file_exists(__DIR__ . '/config/database.local.php')) {
    $_POST['auto_scan'] = 1;
}

if (isset($_POST['auto_scan'])) {
    $domains = ['infinityfree.com', 'epizy.com', 'byetcluster.com'];
    $tested = 0;
    
    $candidateHosts = [];
    if (!empty($dbHost)) {
        $candidateHosts[] = trim($dbHost);
    }
    for ($i = 101; $i <= 350; $i++) {
        foreach ($domains as $d) {
            $candidateHosts[] = "sql{$i}.{$d}";
        }
    }

    foreach ($candidateHosts as $host) {
        $fp = @fsockopen($host, 3306, $errno, $errstr, 0.3);
        if ($fp) {
            fclose($fp);
            $tested++;
            try {
                $dsn = "mysql:host={$host};port=3306;charset=utf8mb4";
                $pdo = new PDO($dsn, $dbUser, $dbPass, [
                    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                    PDO::ATTR_TIMEOUT => 2
                ]);
                $foundHost = $host;
                $dbHost = $host;

                // Auto save config & import schema
                $configContent = "<?php\n"
                    . "// Auto-generated by db-setup.php\n"
                    . "define('DB_HOST', " . var_export($dbHost, true) . ");\n"
                    . "define('DB_PORT', '3306');\n"
                    . "define('DB_NAME', " . var_export($dbName, true) . ");\n"
                    . "define('DB_USER', " . var_export($dbUser, true) . ");\n"
                    . "define('DB_PASS', " . var_export($dbPass, true) . ");\n";
                file_put_contents(__DIR__ . '/config/database.local.php', $configContent);

                $sqlFile = __DIR__ . '/database/import.sql';
                if (file_exists($sqlFile)) {
                    $sql = file_get_contents($sqlFile);
                    $pdo->exec($sql);
                }

                $message = "Found active MySQL Host server ({$host}), saved configuration, and imported database schema successfully! You can now log in.";
                $messageType = "success";
                break;
            } catch (PDOException $e) {
                if ($e->getCode() == 1049 || strpos($e->getMessage(), '1049') !== false) {
                    $foundHost = $host;
                    $dbHost = $host;
                    $message = "Found active MySQL Host server ({$host})! Please ensure database '{$dbName}' is created in InfinityFree vPanel.";
                    $messageType = "success";
                    break;
                }
            }
        }
    }

    if (!$foundHost) {
        $message = "Scanned active MySQL servers. Access denied on all. Check your MySQL Password in InfinityFree Client Area -> Account Details.";
        $messageType = "error";
    }
}

if (isset($_POST['save_config'])) {
    try {
        $dsn = "mysql:host={$dbHost};port=3306;dbname={$dbName};charset=utf8mb4";
        $pdo = new PDO($dsn, $dbUser, $dbPass, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC
        ]);

        $configContent = "<?php\n"
            . "// Auto-generated by db-setup.php\n"
            . "define('DB_HOST', " . var_export($dbHost, true) . ");\n"
            . "define('DB_PORT', '3306');\n"
            . "define('DB_NAME', " . var_export($dbName, true) . ");\n"
            . "define('DB_USER', " . var_export($dbUser, true) . ");\n"
            . "define('DB_PASS', " . var_export($dbPass, true) . ");\n";

        file_put_contents(__DIR__ . '/config/database.local.php', $configContent);

        $sqlFile = __DIR__ . '/database/import.sql';
        if (file_exists($sqlFile)) {
            $sql = file_get_contents($sqlFile);
            $pdo->exec($sql);
        }

        $message = "Database connected and schema imported successfully! You can now log in.";
        $messageType = "success";
    } catch (PDOException $e) {
        $message = "Connection Failed: " . $e->getMessage();
        $messageType = "error";
    } catch (Exception $e) {
        $message = "Setup Error: " . $e->getMessage();
        $messageType = "error";
    }
}
?>
<!DOCTYPE html>
<html lang="en" class="h-full bg-slate-50">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SalesTrack - Database Setup</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" rel="stylesheet">
</head>
<body class="min-h-screen flex items-center justify-center p-4">
    <div class="w-full max-w-lg bg-white rounded-lg shadow-lg border border-slate-200 overflow-hidden">
        <div class="bg-indigo-600 p-6 text-white text-center">
            <h1 class="text-2xl font-bold">SalesTrack Setup</h1>
            <p class="text-indigo-100 text-sm mt-1">Configure and initialize your hosting database</p>
        </div>
        <div class="p-6 space-y-4">
            <?php if ($message): ?>
                <?php if ($messageType === 'success'): ?>
                    <div class="p-4 bg-green-50 border border-green-200 text-green-800 rounded-md text-sm">
                        <div class="font-bold flex items-center gap-2 mb-1">
                            <i class="fas fa-check-circle text-green-600 text-lg"></i>
                            <span>Success!</span>
                        </div>
                        <p><?= htmlspecialchars($message); ?></p>
                        <a href="/login.php" class="inline-block mt-3 px-4 py-2 bg-green-600 text-white font-semibold rounded text-xs uppercase">
                            Go to Sign In &rarr;
                        </a>
                    </div>
                <?php else: ?>
                    <div class="p-4 bg-red-50 border border-red-200 text-red-800 rounded-md text-sm">
                        <div class="font-bold flex items-center gap-2 mb-1">
                            <i class="fas fa-exclamation-triangle text-red-600 text-lg"></i>
                            <span>Connection Error</span>
                        </div>
                        <p class="font-mono text-xs mt-1 break-all"><?= htmlspecialchars($message); ?></p>
                    </div>
                <?php endif; ?>
            <?php endif; ?>

            <form method="POST" class="space-y-4">
                <div>
                    <label class="block text-xs font-semibold uppercase text-slate-600 mb-1">MySQL Hostname (from vPanel)</label>
                    <input type="text" name="db_host" value="<?= htmlspecialchars($dbHost); ?>" required
                           class="w-full px-3 py-2 border border-slate-300 rounded text-sm focus:outline-none focus:border-indigo-500 font-mono"
                           placeholder="e.g. sql302.infinityfree.com">
                </div>
                <div>
                    <label class="block text-xs font-semibold uppercase text-slate-600 mb-1">Database Name</label>
                    <input type="text" name="db_name" value="<?= htmlspecialchars($dbName); ?>" required
                           class="w-full px-3 py-2 border border-slate-300 rounded text-sm font-mono">
                </div>
                <div>
                    <label class="block text-xs font-semibold uppercase text-slate-600 mb-1">MySQL Username</label>
                    <input type="text" name="db_user" value="<?= htmlspecialchars($dbUser); ?>" required
                           class="w-full px-3 py-2 border border-slate-300 rounded text-sm font-mono">
                </div>
                <div>
                    <label class="block text-xs font-semibold uppercase text-slate-600 mb-1">MySQL Password</label>
                    <input type="password" name="db_pass" value="<?= htmlspecialchars($dbPass); ?>" required
                           class="w-full px-3 py-2 border border-slate-300 rounded text-sm font-mono">
                </div>
                <div class="flex gap-3 pt-2">
                    <button type="submit" name="auto_scan" value="1" class="w-1/2 py-3 bg-slate-700 hover:bg-slate-800 text-white font-bold text-xs uppercase rounded shadow flex items-center justify-center gap-2">
                        <i class="fas fa-search"></i> Auto-Detect Server Host
                    </button>
                    <button type="submit" name="save_config" value="1" class="w-1/2 py-3 bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-xs uppercase rounded shadow flex items-center justify-center gap-2">
                        <i class="fas fa-save"></i> Save & Initialize
                    </button>
                </div>
            </form>
        </div>
    </div>
</body>
</html>